name = "rss"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-01-10"

[build]
command = "yarn install && yarn run build"
[build.upload]
format = "service-worker"
